//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneSpravochnik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonent
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public string Phone_Number { get; set; }
        public System.DateTime Date { get; set; }
        public string Adress { get; set; }
        public int DistrictsID { get; set; }
        public int Phone_categoryID { get; set; }
        public int Lgotnaya_categoryID { get; set; }
    
        public virtual District Districts { get; set; }
        public virtual Lgotnaya_category Lgotnaya_category { get; set; }
        public virtual Phone_category Phone_category { get; set; }
    }
}
