//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneSpravochnik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbService : DbContext
    {
        public DbService()
            : base("name=DbService")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonent> Abonents { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Lgotnaya_category> Lgotnaya_category { get; set; }
        public virtual DbSet<Phone_category> Phone_category { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
